// Single source of truth for the site's page metadata.
//
// Used twice, from both sides of the build:
//   • at runtime by `useSeo` (src/useSeo.ts), which rewrites <title>/<meta>/<link rel=canonical>
//     as you navigate the SPA, and
//   • at build time by `seo-plugin.ts`, which bakes the same values into one static HTML file
//     per route so crawlers that do not execute JavaScript (most LLM/answer-engine fetchers,
//     and every social-card unfurler) see real per-page metadata instead of the SPA shell.
// Keeping both readers on this one table is what stops the two from drifting.

/** Canonical origin. Deployed from `main` to Cloudflare Pages. */
export const SITE_URL = "https://brand.posthog.com"
export const SITE_NAME = "PostHog Brand"

/** Social card generated by `site/scripts/gen-brand-icons.ts`. */
export const OG_IMAGE = `${SITE_URL}/og.png`
export const OG_IMAGE_ALT =
  "The PostHog logo above a row of brand colors and five PostHog hedgehog illustrations"

export interface PageSeo {
  /** Route path, without a trailing slash (`/` for the home page). */
  path: string
  /** `<title>`, minus the site-name suffix. */
  title: string
  description: string
  /** Breadcrumb label — usually the nav label rather than the full title. */
  label: string
  /** Static-shell heading + lede used by the prerendered HTML (see `seo-plugin.ts`). */
  headline: string
  /** Keep the page out of search results, and out of the sitemap and nav (the 404 shell). */
  noindex?: boolean
}

/**
 * Every prerendered route, in nav order. `/crests/:slug` is deliberately absent: it is
 * generated per asset at runtime (see `CrestDetailPage`), and listed in the sitemap by the
 * build plugin rather than hard-coded here.
 */
export const PAGES: PageSeo[] = [
  {
    path: "/",
    title: "PostHog brand assets — logo, colors, hedgehogs & crests",
    label: "Overview",
    headline: "PostHog brand assets",
    description:
      "Browse PostHog's brand assets: the logo, the RoundHog typeface, the brand color palette, 160+ hedgehog illustrations, and every team crest — all shipped as the offline React package @posthog/brand.",
  },
  {
    path: "/logo",
    title: "PostHog logo",
    label: "Logo",
    headline: "The PostHog logo",
    description:
      "Every PostHog logo lockup in one parametric React component: landscape, stacked, logomark, and wordmark, in gradient, 4-color print, or mono — plus a logomark that jumps on click.",
  },
  {
    path: "/fonts",
    title: "RoundHog — the PostHog brand typeface",
    label: "Fonts",
    headline: "RoundHog, PostHog's typeface",
    description:
      "RoundHog, PostHog's brand typeface, bundled offline as eight woff2 faces (Regular, Medium, SemiBold, Bold — upright and italic) with ready-to-inject @font-face CSS. No CDN, no loader config.",
  },
  {
    path: "/colors",
    title: "PostHog brand colors",
    label: "Colors",
    headline: "The PostHog color palette",
    description:
      "The PostHog brand color palette with hex values for every core, lighter, and darker tone plus gradients — copyable, and shipped as CSS custom properties and typed JavaScript tokens.",
  },
  {
    path: "/crests",
    title: "PostHog team crests",
    label: "Crests",
    headline: "PostHog team crests",
    description:
      "Every PostHog team crest, in both the full illustration and the mini badge tier — searchable, copyable, and available as tree-shakeable React components, SVG strings, and PNGs.",
  },
  {
    path: "/hoggies",
    title: "PostHog hedgehogs (hoggies)",
    label: "Hoggies",
    headline: "Hoggies — PostHog's hedgehogs",
    description:
      "Search PostHog's library of 160+ hedgehog illustrations — the hoggies — and copy the import for any one. Each ships as a tree-shakeable React component, an inline SVG string, and an optimized PNG.",
  },
]

/**
 * The shell Cloudflare Pages serves — with a real 404 status — for any path that is neither
 * a prerendered route nor a crest. Not in `PAGES`: it must stay out of the sitemap, the
 * cross-page link list, and search results.
 */
export const NOT_FOUND_PAGE: PageSeo = {
  path: "/404",
  title: "Page not found",
  label: "404",
  headline: "Nothing here but spikes",
  description: "This page does not exist on brand.posthog.com.",
  noindex: true,
}

/** Exact-path lookup; returns `undefined` for dynamic or unknown routes. */
export function pageSeo(pathname: string): PageSeo | undefined {
  const path = pathname.length > 1 ? pathname.replace(/\/+$/, "") : pathname
  return PAGES.find((page) => page.path === path)
}

/** `<title>` text for a page — the home page already reads as a full title on its own. */
export function documentTitle(title: string, path: string): string {
  return path === "/" ? title : `${title} · ${SITE_NAME}`
}

/** Absolute, canonical URL for a route path. */
export function canonicalUrl(path: string): string {
  return path === "/" ? `${SITE_URL}/` : `${SITE_URL}${path}`
}

/**
 * schema.org breadcrumb trail for a page. Answer engines and search results use it to show
 * where a page sits, and it is cheap to emit for a two-level site.
 */
export function breadcrumbJsonLd(path: string, label: string): string {
  const items = [{ name: SITE_NAME, item: canonicalUrl("/") }]
  if (path !== "/") items.push({ name: label, item: canonicalUrl(path) })
  return JSON.stringify({
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((entry, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: entry.name,
      item: entry.item,
    })),
  })
}
