// Generate src/generated/** from ./assets. Pure and deterministic: same assets in,
// byte-identical output out. Run with `pnpm codegen` (also runs as prebuild/pretest).
//
// Layout (per export group <path> — "hoggies", "logo", "crests/full", "crests/mini"):
//   generated/<path>/meta/<slug>.ts        — AssetMeta
//   generated/<path>/svg/<slug>.ts         — viewBox, body, svg strings
//   generated/<path>/png/<slug>.ts         — bundled PNG url + aspectRatio
//   generated/<path>/components/<slug>.tsx — inline-SVG React component
//   generated/<path>/{components,svg,png}/index.ts, manifest.ts
// Plus generated/manifest.ts (all groups) and generated/colors/{tokens,css}.ts.
//
// Crests fan out into two groups, one per size tier; their SVG/PNG sources live under
// assets/crests/<tier>/{vectors,png}/, while every other namespace reads assets/<ns>/.
// Renames (scripts/lib/renames.ts) are a presentation layer: inputs are read by the
// on-disk (Figma) slug, everything emitted is keyed by the published slug.

import { readFile, mkdir, rm, writeFile } from "node:fs/promises"
import { existsSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import type { Catalog, CatalogEntry } from "./lib/catalog.ts"
import { colors } from "../static/colors.ts"
import { svgBody } from "./lib/svg.ts"
import { assertNoCollisions, componentName, pngConstName, svgConstName } from "./lib/naming.ts"
import { applyRename, titleFromSlug } from "./lib/renames.ts"
import { inferVariants } from "./lib/variants.ts"
import { ASSET_GROUPS, type AssetGroup, type CrestTier, type Namespace } from "../src/types.ts"

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..")
const ASSETS = join(ROOT, "assets")
const OUT = join(ROOT, "src", "generated")

const HEADER = "// AUTO-GENERATED by scripts/codegen.ts — do not edit.\n"
const VIEWBOX_RE = /viewBox\s*=\s*["']([^"']+)["']/i

/**
 * A catalog entry with the offline presentation layers applied. `slug`/`name` are the
 * *published* values that back the component + `AssetMeta` (for a variant family this is
 * the shared base, e.g. "noir"). `moduleKey` is the unique per-file/per-const key
 * driving module filenames, the svg/png export identifiers, and the deep-import subpaths
 * (the published slug for a normal asset, `<base>-<variant>` for a family member).
 * `sourceSlug` is the on-disk (Figma) slug used to read the SVG input and reference the
 * bundled PNG that `tsdown` copies from `assets/`. `variantKey` (when set) is the value
 * of the `variant` prop this entry renders.
 */
type GeneratedEntry = CatalogEntry & {
  sourceSlug: string
  moduleKey: string
  variantKey?: string
  isDefaultVariant?: boolean
}

/** Throws if two source slugs collide onto the same module key (would overwrite files). */
function assertUniqueModuleKeys(group: AssetGroup, entries: GeneratedEntry[]): void {
  const seen = new Map<string, string>()
  for (const e of entries) {
    const prev = seen.get(e.moduleKey)
    if (prev !== undefined && prev !== e.sourceSlug) {
      throw new Error(
        `Collision in "${group.path}": "${prev}" and "${e.sourceSlug}" both produce module key ` +
          `"${e.moduleKey}". Fix scripts/lib/renames.ts.`,
      )
    }
    seen.set(e.moduleKey, e.sourceSlug)
  }
}

/** A safe lowerCamel identifier for a group path, e.g. "crests/full" -> "crestsFull". */
function groupIdent(group: AssetGroup): string {
  return group.path
    .split("/")
    .map((seg, i) => {
      const camel = seg.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase())
      return i === 0 ? camel : camel.charAt(0).toUpperCase() + camel.slice(1)
    })
    .join("")
}

/** "../" repeated `n` times. */
function up(n: number): string {
  return "../".repeat(n)
}

/** Relative path from a generated `<group>/<kind>/<file>` back to `src/`. */
function kindToSrc(group: AssetGroup): string {
  return up(group.path.split("/").length + 2)
}

/** Relative path from a generated `<group>/manifest.ts` back to `src/`. */
function manifestToSrc(group: AssetGroup): string {
  return up(group.path.split("/").length + 1)
}

/** On-disk folder holding a group's SVG/PNG sources (tiered crests nest under `<tier>/`). */
function sourceDir(namespace: Namespace, tier?: CrestTier): string {
  return tier ? join(ASSETS, namespace, tier) : join(ASSETS, namespace)
}

async function writeOut(relPath: string, content: string): Promise<void> {
  const full = join(OUT, relPath)
  await mkdir(dirname(full), { recursive: true })
  await writeFile(full, content)
}

/** Read a namespace catalog and return only the entries belonging to `group` (its tier). */
async function readGroupEntries(group: AssetGroup): Promise<CatalogEntry[]> {
  const path = join(ASSETS, group.namespace, "catalog.json")
  if (!existsSync(path)) return []
  const catalog = JSON.parse(await readFile(path, "utf8")) as Catalog
  return catalog.entries.filter((e) => e.tier === group.tier)
}

/**
 * A group's catalog entries with the presentation layers applied, in order: renames
 * (scripts/lib/renames.ts) rewrite the slug, then a renamed slug that reads as a numbered
 * family member (scripts/lib/variants.ts) collapses onto its base slug with a
 * `variantKey`. Emitted keyed by the published slug/moduleKey; inputs are still read by
 * the on-disk `sourceSlug`.
 */
async function generatedEntries(group: AssetGroup): Promise<GeneratedEntry[]> {
  const catalog = await readGroupEntries(group)
  const renamed = catalog.map((entry) => ({
    entry,
    ...applyRename(group.namespace, entry.slug, entry.name),
  }))

  // Variant grouping is inferred from the group's whole slug set, so it must be built
  // from the renamed slugs before any single entry can be resolved.
  const variants = inferVariants(renamed.map((r) => r.slug))

  return renamed.map(({ entry, slug, name }) => {
    const variant = variants.resolve(slug)
    if (variant) {
      return {
        ...entry,
        slug: variant.baseSlug,
        name: titleFromSlug(variant.baseSlug),
        sourceSlug: entry.slug,
        moduleKey: slug,
        variantKey: variant.variant,
        isDefaultVariant: variant.isDefault,
      }
    }

    return { ...entry, slug, name, sourceSlug: entry.slug, moduleKey: slug }
  })
}

async function main(): Promise<void> {
  // Fresh output every run keeps determinism (no stale modules from removed assets).
  await rm(OUT, { recursive: true, force: true })
  await mkdir(OUT, { recursive: true })

  let total = 0
  for (const group of ASSET_GROUPS) {
    // Read inputs by the catalog (Figma) slug; emit everything by the published slug.
    const entries = await generatedEntries(group)
    assertUniqueModuleKeys(group, entries)
    // svg/png modules + string/url exports are keyed by moduleKey — assert those names
    // don't collide. Component exports are keyed by the published slug (one per bare
    // asset, one per variant family's base) — assert those don't collide either.
    assertNoCollisions(
      group.namespace,
      entries.map((e) => e.moduleKey),
      group.tier,
    )
    assertNoCollisions(
      group.namespace,
      [
        ...entries.filter((e) => !e.variantKey).map((e) => e.slug),
        ...new Set(entries.filter((e) => e.variantKey).map((e) => e.slug)),
      ],
      group.tier,
    )

    for (const entry of entries) {
      await writeMeta(group, entry)
      await writeSvg(group, entry)
      await writePng(group, entry)
      // A variant family member has no standalone component; the family ships one
      // compound component (emitted below) that switches on the `variant` prop.
      if (!entry.variantKey) await writeComponent(group, entry)
    }
    for (const [baseSlug, variants] of groupVariants(entries)) {
      await writeVariantComponent(group, baseSlug, variants)
    }
    await writeBarrels(group, entries)
    await writeGroupManifest(group, entries)
    total += entries.length
    console.log(`codegen: ${group.path} — ${entries.length} assets`)
  }

  await writeCombinedCrests()
  await writeRootManifest()
  await writeColors()
  console.log(`codegen: ${total} assets across ${ASSET_GROUPS.length} groups → src/generated`)
}

/**
 * TSDoc for a combined-barrel crest (`@posthog/brand/crests`). `kind` reflects which tiers
 * exist: `both` documents the compound base + `.Mini`, `full`/`mini` document a single tier.
 */
function crestCombinedDoc(name: string, display: string, kind: "both" | "full" | "mini"): string {
  const lines = ["/**"]
  if (kind === "both") {
    lines.push(
      ` * The **${display}** crest. Use the base for the full illustration, and \`.Mini\` for the`,
      " * simplified badge that reads at small sizes (favicons, avatars, inline chips).",
      " *",
      " * Pass `size`, `title`, and any other `<svg>` prop to either.",
      " *",
      " * @example",
      " * ```tsx",
      ` * import { ${name} } from "@posthog/brand/crests"`,
      " *",
      ` * <${name} size={64} title=${JSON.stringify(`${display} crest`)} /> // full illustration`,
      ` * <${name}.Mini size={24} />${" ".repeat(Math.max(1, 24 - name.length))}// the mini badge`,
      " * ```",
    )
  } else if (kind === "full") {
    lines.push(
      ` * The **${display}** crest. This crest only comes as the full illustration — it has no`,
      " * `.Mini` badge.",
      " *",
      " * Pass `size`, `title`, and any other `<svg>` prop.",
      " *",
      " * @example",
      " * ```tsx",
      ` * import { ${name} } from "@posthog/brand/crests"`,
      " *",
      ` * <${name} size={64} title=${JSON.stringify(`${display} crest`)} />`,
      " * ```",
    )
  } else {
    lines.push(
      ` * The **${display}** crest. This crest only comes as the mini badge, so the base and`,
      " * `.Mini` are the same illustration.",
      " *",
      " * Pass `size`, `title`, and any other `<svg>` prop.",
      " *",
      " * @example",
      " * ```tsx",
      ` * import { ${name} } from "@posthog/brand/crests"`,
      " *",
      ` * <${name} size={24} title=${JSON.stringify(`${display} crest`)} />`,
      " * ```",
    )
  }
  lines.push(" */")
  return lines.join("\n")
}

/**
 * Emit the combined `@posthog/brand/crests` barrel: one `<Name>Crest` per crest slug that
 * renders the full illustration, with the mini badge attached as `<Name>Crest.Mini` (a
 * compound component). Full-only slugs have no `.Mini`; a mini-only slug uses the mini as
 * the base. The tier-specific `crests/full` and `crests/mini` barrels are unaffected.
 */
async function writeCombinedCrests(): Promise<void> {
  const fullGroup = ASSET_GROUPS.find((g) => g.namespace === "crests" && g.tier === "full")
  const miniGroup = ASSET_GROUPS.find((g) => g.namespace === "crests" && g.tier === "mini")
  const full = new Map((fullGroup ? await generatedEntries(fullGroup) : []).map((e) => [e.slug, e]))
  const mini = new Map((miniGroup ? await generatedEntries(miniGroup) : []).map((e) => [e.slug, e]))

  const slugs = [...new Set([...full.keys(), ...mini.keys()])].sort()
  if (!slugs.length) return

  const byName = new Map<string, string>()
  const exportLines: string[] = []

  const TYPE_IMPORT = `import type { SvgAssetComponent } from "../../runtime/create-svg-asset.tsx";\n`

  for (const slug of slugs) {
    const hasFull = full.has(slug)
    const hasMini = mini.has(slug)
    // The combined name is the un-tiered crest name,
    // identical to the full tier's export (e.g. "MarketingCrest");
    // the mini is "<Name>CrestMini" (e.g. "MarketingCrestMini").
    const name = componentName("crests", slug)
    const miniName = componentName("crests", slug, "mini")
    const clash = byName.get(name)
    if (clash !== undefined && clash !== slug) {
      throw new Error(
        `Combined crest name collision: "${clash}" and "${slug}" both map to ${name}.`,
      )
    }
    byName.set(name, slug)

    const display = (full.get(slug) ?? mini.get(slug))!.name

    let content: string
    if (hasFull && hasMini) {
      // Re-export the full as the base with the mini attached as `.Mini` (compound
      // component). The full import is aliased because it shares the combined name.
      content =
        `${HEADER}${TYPE_IMPORT}` +
        `import { ${name} as Full } from "./full/components/${slug}.tsx";\n` +
        `import { ${miniName} } from "./mini/components/${slug}.tsx";\n\n` +
        crestCombinedDoc(name, display, "both") +
        "\n" +
        `export const ${name}: SvgAssetComponent & { Mini: SvgAssetComponent } = Object.assign(\n` +
        `  Full,\n  { Mini: ${miniName} },\n);\n\n` +
        `export default ${name};\n`
    } else if (hasFull) {
      // Full-only: a plain re-export — no `.Mini`, same binding as `crests/full`.
      content =
        `${HEADER}${crestCombinedDoc(name, display, "full")}\n` +
        `export { ${name}, ${name} as default } from "./full/components/${slug}.tsx";\n`
    } else {
      // Mini-only: the mini is the base, and is also exposed as `.Mini`.
      content =
        `${HEADER}${TYPE_IMPORT}` +
        `import { ${miniName} } from "./mini/components/${slug}.tsx";\n\n` +
        crestCombinedDoc(name, display, "mini") +
        "\n" +
        `export const ${name}: SvgAssetComponent & { Mini: SvgAssetComponent } = Object.assign(\n` +
        `  ${miniName},\n  { Mini: ${miniName} },\n);\n\n` +
        `export default ${name};\n`
    }

    await writeOut(`crests/${slug}.tsx`, content)
    exportLines.push(`export { ${name} } from "./${slug}.tsx";`)
  }

  await writeOut("crests/index.ts", `${HEADER}${exportLines.join("\n")}\n`)
  console.log(`codegen: crests (combined) — ${slugs.length} components`)
}

async function writeMeta(group: AssetGroup, entry: GeneratedEntry): Promise<void> {
  // A variant-family member records its selector as `variant: { variant: "<key>" }` (the
  // value passed as the `variant` prop); a crest COMPONENT_SET carries its Figma variant
  // properties. Both live in the same `variant` field and are mutually exclusive here.
  const variant = entry.variantKey ? { variant: entry.variantKey } : entry.variant
  const meta = {
    slug: entry.slug,
    name: entry.name,
    namespace: entry.namespace,
    ...(entry.tier ? { tier: entry.tier } : {}),
    figmaNodeId: entry.figmaNodeId,
    aspectRatio: entry.aspectRatio,
    ...(variant ? { variant } : {}),
    ...(entry.tags?.length ? { tags: entry.tags } : {}),
  }
  await writeOut(
    `${group.path}/meta/${entry.moduleKey}.ts`,
    `${HEADER}import type { AssetMeta } from "${kindToSrc(group)}types.ts";\n\n` +
      `export const meta: AssetMeta = ${JSON.stringify(meta, null, 2)};\n\n` +
      `export default meta;\n`,
  )
}

async function writeSvg(group: AssetGroup, entry: GeneratedEntry): Promise<void> {
  const raw = (
    await readFile(
      join(sourceDir(group.namespace, group.tier), "vectors", `${entry.sourceSlug}.svg`),
      "utf8",
    )
  ).trim()
  const viewBox = raw.match(VIEWBOX_RE)?.[1]?.trim() ?? "0 0 0 0"
  const body = svgBody(raw)
  await writeOut(
    `${group.path}/svg/${entry.moduleKey}.ts`,
    `${HEADER}` +
      `export const viewBox: string = ${JSON.stringify(viewBox)};\n` +
      `export const body: string = ${JSON.stringify(body)};\n` +
      `export const svg: string = ${JSON.stringify(raw)};\n\n` +
      `export default svg;\n`,
  )
}

async function writePng(group: AssetGroup, entry: GeneratedEntry): Promise<void> {
  // The PNG is copied next to this module in dist (see tsdown.config copy) under its
  // on-disk Figma name, so the URL references the source slug even when renamed.
  await writeOut(
    `${group.path}/png/${entry.moduleKey}.ts`,
    `${HEADER}` +
      `export const src: string = new URL(${JSON.stringify(`./${entry.sourceSlug}.png`)}, import.meta.url).href;\n` +
      `export const aspectRatio: number = ${entry.aspectRatio};\n\n` +
      `export default src;\n`,
  )
}

/** Example `size` (px) used in a generated component's `@example`, scaled per group. */
function exampleSize(group: AssetGroup): number {
  if (group.namespace === "hoggies") return 120
  return group.tier === "mini" ? 24 : 64
}

/** One-line identity for a single-asset component's TSDoc, e.g. "The **Doc Brown** …". */
function assetLead(group: AssetGroup, entry: GeneratedEntry): string {
  if (group.namespace === "hoggies") return `The **${entry.name}** hedgehog illustration`
  if (group.tier === "mini") return `The **${entry.name}** crest — the simplified mini badge`
  return `The **${entry.name}** crest — the full illustration`
}

/**
 * The TSDoc block emitted above each generated component: a one-line identity, the shared
 * `size`/`title` usage note, and a copy-pasteable `@example` keyed to the asset's real name
 * and import subpath. Every component gets one, so editor IntelliSense describes each asset
 * (and its usage) on hover.
 */
function componentDoc(group: AssetGroup, entry: GeneratedEntry, name: string): string {
  return [
    "/**",
    ` * ${assetLead(group, entry)}, as a React component.`,
    " *",
    " * Pass `size` to set the width (height follows automatically), and `title` to give it an",
    " * accessible label. Accepts any other `<svg>` prop (`className`, `style`, `onClick`, …).",
    " *",
    " * @example",
    " * ```tsx",
    ` * import { ${name} } from "@posthog/brand/${group.path}"`,
    " *",
    ` * <${name} size={${exampleSize(group)}} title=${JSON.stringify(entry.name)} />`,
    " * ```",
    " */",
  ].join("\n")
}

async function writeComponent(group: AssetGroup, entry: GeneratedEntry): Promise<void> {
  const name = componentName(group.namespace, entry.slug, group.tier)
  await writeOut(
    `${group.path}/components/${entry.moduleKey}.tsx`,
    `${HEADER}import { createSvgAsset, type SvgAssetComponent } from "${kindToSrc(group)}runtime/create-svg-asset.tsx";\n` +
      `import { body, viewBox } from "../svg/${entry.moduleKey}.ts";\n` +
      `import { meta } from "../meta/${entry.moduleKey}.ts";\n\n` +
      `${componentDoc(group, entry, name)}\n` +
      `export const ${name}: SvgAssetComponent = createSvgAsset({ viewBox, body, meta });\n\n` +
      `export default ${name};\n`,
  )
}

/**
 * Group a group's entries by base slug, keeping only the variant families. Members are
 * sorted numerically by variant key, so `variant` unions and the default read `1, 2, …`
 * regardless of the catalog's (alphabetical) order — `10` after `9`, not after `1`.
 */
function groupVariants(entries: GeneratedEntry[]): Map<string, GeneratedEntry[]> {
  const groups = new Map<string, GeneratedEntry[]>()
  for (const e of entries) {
    if (!e.variantKey) continue
    const list = groups.get(e.slug) ?? []
    list.push(e)
    groups.set(e.slug, list)
  }

  for (const list of groups.values()) {
    list.sort((a, b) => Number(a.variantKey) - Number(b.variantKey))
  }

  return groups
}

/** TSDoc for a variant compound component: identity + the `variant` prop, with an example. */
function variantComponentDoc(name: string, display: string, keys: string[]): string {
  const list = keys.map((k) => `\`"${k}"\``).join(", ")
  return [
    "/**",
    ` * The **${display}** hedgehog illustration, as a React component. It comes in`,
    ` * ${keys.length} variants — pass \`variant\` (${list}) to pick one; it defaults to`,
    ` * \`"${keys[0]}"\`.`,
    " *",
    " * Pass `size` to set the width (height follows automatically), and `title` to give it an",
    " * accessible label. Accepts any other `<svg>` prop (`className`, `style`, `onClick`, …).",
    " *",
    " * @example",
    " * ```tsx",
    ` * import { ${name} } from "@posthog/brand/hoggies"`,
    " *",
    ` * <${name} size={120} title=${JSON.stringify(display)} />`,
    ` * <${name} variant=${JSON.stringify(keys[keys.length - 1])} size={120} />`,
    " * ```",
    " */",
  ].join("\n")
}

/**
 * Emit one compound `Hedgehog<Base>` for a variant family: it bundles each member's
 * inline SVG and switches on the `variant` prop, defaulting to the lowest-numbered one.
 * The individual members ship no standalone component (only their svg/png/meta modules).
 * `variants` arrives pre-sorted by variant key (see `groupVariants`).
 */
async function writeVariantComponent(
  group: AssetGroup,
  baseSlug: string,
  ordered: GeneratedEntry[],
): Promise<void> {
  const name = componentName(group.namespace, baseSlug, group.tier)
  const keys = ordered.map((v) => v.variantKey!)
  const union = keys.map((k) => JSON.stringify(k)).join(" | ")
  const defaultEntry = ordered.find((v) => v.isDefaultVariant) ?? ordered[0]!

  const imports = ordered
    .map((v, i) => `import { viewBox as vb${i}, body as b${i} } from "../svg/${v.moduleKey}.ts";`)
    .join("\n")
  const variantMap = ordered
    .map((v, i) => `  ${JSON.stringify(v.variantKey!)}: { viewBox: vb${i}, body: b${i} },`)
    .join("\n")
  const orderLiteral = keys.map((k) => JSON.stringify(k)).join(", ")

  await writeOut(
    `${group.path}/components/${baseSlug}.tsx`,
    `${HEADER}import { createVariantSvgAsset, type VariantSvgAssetComponent } from "${kindToSrc(group)}runtime/create-variant-svg-asset.tsx";\n` +
      `${imports}\n` +
      `import { meta } from "../meta/${defaultEntry.moduleKey}.ts";\n\n` +
      `${variantComponentDoc(name, defaultEntry.name, keys)}\n` +
      `export const ${name}: VariantSvgAssetComponent<${union}> = createVariantSvgAsset({\n` +
      `  variants: {\n${variantMap}\n  },\n` +
      `  order: [${orderLiteral}],\n` +
      `  defaultVariant: ${JSON.stringify(defaultEntry.variantKey!)},\n` +
      `  meta,\n});\n\n` +
      `export default ${name};\n`,
  )
}

async function writeBarrels(group: AssetGroup, entries: GeneratedEntry[]): Promise<void> {
  // Component exports: one per bare asset, one compound per variant family (its members
  // have no standalone component). Sorted by export name for a stable barrel.
  const bases = new Map<string, string>() // baseSlug -> component name (dedupes a family)
  for (const e of entries) {
    if (e.variantKey) bases.set(e.slug, componentName(group.namespace, e.slug, group.tier))
  }
  const componentExports = [
    ...entries
      .filter((e) => !e.variantKey)
      .map((e) => ({
        name: componentName(group.namespace, e.slug, group.tier),
        file: e.moduleKey,
      })),
    ...[...bases].map(([baseSlug, name]) => ({ name, file: baseSlug })),
  ].sort((a, b) => a.name.localeCompare(b.name))
  const components = componentExports.map((c) => `export { ${c.name} } from "./${c.file}.tsx";`)
  await writeOut(`${group.path}/components/index.ts`, `${HEADER}${components.join("\n")}\n`)

  // svg/png string + url exports stay one-per-member, keyed by moduleKey.
  const svgs = entries.map(
    (e) =>
      `export { svg as ${svgConstName(group.namespace, e.moduleKey, group.tier)} } from "./${e.moduleKey}.ts";`,
  )
  await writeOut(`${group.path}/svg/index.ts`, `${HEADER}${svgs.join("\n")}\n`)

  const pngs = entries.map(
    (e) =>
      `export { src as ${pngConstName(group.namespace, e.moduleKey, group.tier)} } from "./${e.moduleKey}.ts";`,
  )
  await writeOut(`${group.path}/png/index.ts`, `${HEADER}${pngs.join("\n")}\n`)
}

async function writeGroupManifest(group: AssetGroup, entries: GeneratedEntry[]): Promise<void> {
  const imports = entries
    .map((e, i) => `import { meta as m${i} } from "./meta/${e.moduleKey}.ts";`)
    .join("\n")
  const array = entries.map((_, i) => `  m${i},`).join("\n")
  await writeOut(
    `${group.path}/manifest.ts`,
    `${HEADER}import type { AssetMeta } from "${manifestToSrc(group)}types.ts";\n${imports}\n\n` +
      `export const assets: AssetMeta[] = [\n${array}\n];\n`,
  )
}

async function writeRootManifest(): Promise<void> {
  const imports = ASSET_GROUPS.map(
    (g) => `import { assets as ${groupIdent(g)} } from "./${g.path}/manifest.ts";`,
  ).join("\n")
  const spread = ASSET_GROUPS.map((g) => `  ...${groupIdent(g)},`).join("\n")
  await writeOut(
    "manifest.ts",
    `${HEADER}import type { AssetMeta } from "../types.ts";\n${imports}\n\n` +
      `export const allAssets: AssetMeta[] = [\n${spread}\n];\n`,
  )
}

async function writeColors(): Promise<void> {
  await writeOut(
    "colors/tokens.ts",
    `${HEADER}import type { BrandColors } from "../../types.ts";\n\n` +
      `export const colors: BrandColors = ${JSON.stringify(colors, null, 2)};\n\n` +
      `export default colors;\n`,
  )

  // CSS custom properties: --posthog-<key>[-lighter|-darker], plus a gradient.
  const lines: string[] = [":root {"]
  for (const [key, c] of Object.entries(colors)) {
    lines.push(`  --posthog-${key}: ${c.core};`)
    lines.push(`  --posthog-${key}-lighter: ${c.lighter};`)
    lines.push(`  --posthog-${key}-darker: ${c.darker};`)
    lines.push(
      `  --posthog-${key}-gradient: linear-gradient(180deg, ${c.gradient[0]} 0%, ${c.gradient[1]} 100%);`,
    )
  }
  lines.push("}")
  await writeOut(
    "colors/css.ts",
    `${HEADER}export const colorsCss: string = ${JSON.stringify(lines.join("\n") + "\n")};\n\n` +
      `export default colorsCss;\n`,
  )
}

await main()
